config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'serssions/new'

  resources :microposts
  resources :users
  
  get '/home', to: 'static_pages#home'

  get '/help', to:'static_pages#help'

  get '/about', to:'static_pages#about'

  get '/signup', to:'users#new'

  post 'signup', to: 'users#create'

  get '/login', to:'sessions#new'

  post 'login', to:'sessions#create'

  delete '/logout', to:'sessions#destroy'
   
  root "static_pages#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
	belongs_to :user
	validates :content, length:{maximum: 140},
			           presence: true
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	has_many :microposts
	attr_accessor :remember_token

	before_save { self.name.downcase!; self.email.downcase! }

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	VALID_NAME_REGEX = /\A[\w+\-.]/i

	validates :name, presence: true, length:{minimum: 6, maximum: 20},
			   format: { with: VALID_NAME_REGEX }
			   
	validates :email, presence: true, length:{maximum: 50},
			  format: { with: VALID_EMAIL_REGEX },
			  uniqueness: { case_sensitive: false }


	# returns a hash digest of a given string
	def User.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    	BCrypt::Password.create(string, cost: cost)
	end

	def User.new_token
		return SecureRandom.urlsafe_base64
	end


	def remember
		self.remember_token = User.new_token
		update_attribute(:remember_digest, User.digest(self.remember_token))
	end

	# Returns true if the give token matchs the digest
	def authenticated?(remember_token)
		BCrypt::Password.new(remember_digest).is_password?(remember_token)
	end

	# Forgets a user.
  	def forget
    	update_attribute(:remember_digest, nil)
  	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :set_micropost, only: [:show, :edit, :update, :destroy]

  # GET /microposts
  # GET /microposts.json
  def index
    @microposts = Micropost.all
  end

  # GET /microposts/1
  # GET /microposts/1.json
  def show
  end

  # GET /microposts/new
  def new
    @micropost = Micropost.new
  end

  # GET /microposts/1/edit
  def edit
  end

  # POST /microposts
  # POST /microposts.json
  def create
    @micropost = Micropost.new(micropost_params)

    respond_to do |format|
      if @micropost.save
        format.html { redirect_to @micropost, notice: 'Micropost was successfully created.' }
        format.json { render :show, status: :created, location: @micropost }
      else
        format.html { render :new }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /microposts/1
  # PATCH/PUT /microposts/1.json
  def update
    respond_to do |format|
      if @micropost.update(micropost_params)
        format.html { redirect_to @micropost, notice: 'Micropost was successfully updated.' }
        format.json { render :show, status: :ok, location: @micropost }
      else
        format.html { render :edit }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    @micropost.destroy
    respond_to do |format|
      format.html { redirect_to microposts_url, notice: 'Micropost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micropost
      @micropost = Micropost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def micropost_params
      params.require(:micropost).permit(:content, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
  	if logged_in?
  		log_out current_user
  		flash[:success] = 'Logout Successful'
  		redirect_to root_path
  	else
  		render json: 'Invalid Request'
  	end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    if current_user
      log_out current_user
    end

    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end
    
  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        flash[:success] = 'User was successfully created!'
        log_in @user
        remember @user
        redirect_to @user
      else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
      end
    end
  end


  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        flash[:success] = 'User was successfully created!'
        format.html { redirect_to @user}
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    log_out
    redirect_to root_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :dob, :bio, :blah)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(name='')
		if name == ''
			return 'Microblog'
	    else
	    	return name + ' | MB'
	    end
	end

end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def log_in(user)
		session[:user_id] = user.id
	end

	# Remembers a user in a persistent session
	def remember(user)
		user.remember
		cookies.permanent.signed[:user_id] = user.id
		cookies.permanent[:remember_token] = user.remember_token
	end

 	def current_user
	    if (user_id = session[:user_id])
	    	@current_user ||= User.find_by(id: user_id)
	    elsif (user_id = cookies.signed[:user_id])
			user = User.find_by(id: user_id)
			if user && user.authenticated?(cookies[:remember_token])
				log_in user
		    	@current_user = user
		  	end
	    end
  	end

	def logged_in?
		!current_user.nil?
	end

	# Forgets a persistent session.
  	def forget(user)
	    user.forget
	    cookies.delete(:user_id)
	    cookies.delete(:remember_token)
  	end

  	# Logs out the current user.
  	def log_out
	    forget(current_user)
	    session.delete(:user_id)
	    @current_user = nil
  	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
 <!-- This is the navbar section -->
 <header class='navbar navbar-fixed-top navbar-inverse'>
  <div class='container'>
    <%= link_to 'Mirco Blog', root_path , id: 'logo' %>
     <nav>
	  <ul class='nav navbar-nav navbar-right'>
	    <li><%= link_to 'Help', help_path %></li>
	    <li><%= link_to 'About', about_path %></li>
	    <% if !logged_in? %>
	      <li><%= link_to 'Log in', login_path %></li>
	    <% else %>
	      <li><%= link_to 'Users', users_path %></li>
	      <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
	    <% end %>
	  </ul>
	</nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<%# 
  fills the appropriate title for the page.
  fills "Microblog" if nothing is provided.
%>
<% @title = full_title(yield(:title)) %>

<!DOCTYPE html>
<html>
  <head>
    <title><%= @title %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class='container'>
    <%= render 'shared/flash_messages' %>
    <div class='content'>
      <%= yield %>
    </div>
      <%= render 'layouts/footer' %>
    </div>

    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/microposts/_form.html.erb
<%= form_for(micropost) do |f| %>
  <% if micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
      <% micropost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_field :content %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/microposts/edit.html.erb
<h1>Editing Micropost</h1>

<%= render 'form', micropost: @micropost %>

<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>

app/views/microposts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Microposts</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @microposts.each do |micropost| %>
      <tr>
        <td><%= micropost.content %></td>
        <td><%= micropost.user_id %></td>
        <td><%= link_to 'Show', micropost %></td>
        <td><%= link_to 'Edit', edit_micropost_path(micropost) %></td>
        <td><%= link_to 'Destroy', micropost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Micropost', new_micropost_path %>

app/views/microposts/new.html.erb
<h1>New Micropost</h1>

<%= render 'form', micropost: @micropost %>

<%= link_to 'Back', microposts_path %>

app/views/microposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @micropost.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @micropost.user_id %>
</p>

<%= link_to 'Edit', edit_micropost_path(@micropost) %> |
<%= link_to 'Back', microposts_path %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_messages.html.erb
  	
<!-- partial to handle rendering flash messages -->
<% flash.each do |key, val| %>
	<% if key == 'notice' %>
		<p class="alert alert-info"><%= val %></p>
	<% elsif key == 'danger' %>
		<p class="alert alert-danger"><%= val %></p>
	<% elsif key == 'success' %>
		<p class="alert alert-success"><%= val %></p>
	<% end %>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>

<h1>About</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://www.railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
  book</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://www.railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
  book</a>.
</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<div class="center jumbotron">
  <h1>Welcome to the Micro Blog</h1>

  <h2>
    This is the home page for Micro blog. The place where you share your story with the world!
  </h2>

  <%= link_to "Sign up now!", signup_path , class: "btn btn-lg btn-primary" %>
</div>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>

  <div class='row'>
    <div class='col-md-6 col-md-offset-3'>

      <%= render 'shared/error_messages' %>

      <div class="field center">
        <%= f.text_field :name, class: 'form-control',  placeholder: 'Name' %>
      </div>

      <div class="field center">
        <%= f.text_field :email, class: 'form-control', placeholder: 'Email' %>
      </div>

       <div class="field center">
        <%= f.password_field :password, class: 'form-control', placeholder: 'Password' %>
      </div>

      <div class="field center">
        <%= f.password_field :password_confirmation, class: 'form-control', placeholder: 'Confirm Password' %>
      </div>

      <div class="actions center">
        <%= f.submit 'Create!', class: "btn btn-primary" %>
      </div>
    </div>
  </div>

<% end %>

app/views/users/_update_form.html.erb
<%= form_for(user) do |f| %>

  <div class='row'>
    <div class='col-md-4 col-md-offset-4'>
      <div class='card' style='margin-top: 60px;'>
        <h1>Edit Profile</h1>

        <%= render 'shared/error_messages' %>

        <div class="field center">
          <%= f.text_field :name, class: 'form-control',  placeholder: 'Name' %>
        </div>

        <div class="field center">
          <%= f.text_field :email, class: 'form-control', placeholder: 'Email' %>
        </div>

        <div class="field center">
          <%= f.text_area :bio, class: 'form-control', placeholder: 'About You' %>
        </div>

        <div class="actions center">
          <%= f.submit 'Update Info', class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>

<% end %>

app/views/users/edit.html.erb
<%= render 'update_form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table class='table'>
  <thead class="thead">
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div class='container'>
  <div class='row'>
  	<div class='col-md-6 col-md-offset-3 card'>
	  <h2><%= @user.name.capitalize %></h2>

	  <h4>About</h4>

	  <p style='margin-top: 40px; margin-left: 20px;'><%= @user.bio %></p>

	  <div class='container' style="margin-top: 50px;">
		<%= link_to 'Edit', edit_user_path(@user) , {class: 'btn btn-primary' } %>
		<%= link_to 'Back', users_path, { class: 'btn btn-primary', style: 'float: left'}; %>
	  </div>

    </div>
  </div>
</div>